build:
  skipPoetryInstall: true

services:
  - type: web
    name: leaf-disease-detector
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: development  
